### ISSUE TITLE
Latest HTML5 Bot API Update

### ISSUE THREAD

**Issue by kamikazechaser** [GochoMugo/node-telegram-bot-api#32]

**Comment by kamikazechaser** [comment]
Initial support for HTML5 games coming soon!

**Comment by GochoMugo** [comment]
There's a [PR](https://github.com/yagop/node-telegram-bot-api/pull/201) addressing this. But I have not found time to go through the games feature yet.

**Comment by kamikazechaser** [comment]
Let me go through it and see if I can hook up a game too !
