### ISSUE TITLE
Forwarded message event

### ISSUE THREAD

**Issue by BeInLife** [GochoMugo/node-telegram-bot-api#35]
Hello, is it possible to monitor forwarded messages with bot.on() method?

**Comment by GochoMugo** [comment]
I have **not** worked with forwarded messages before but from the API documentation, a forwarded message would qualify as an **update** that the bot receives/fetches. If so, then it is possible to handle them, like:

``` js
bot.on("message", function(msg) {
    // These will be defined if 'msg' has been forwarded
    console.log(msg.forward_from);
    console.log(msg.forward_from_chat); // for channels
    console.log(msg.forward_date); 
});
```

See [the API documentation on Message type](https://core.telegram.org/bots/api#message).

**Comment by BeInLife** [comment]
Thanks
