### ISSUE TITLE
Callback Query documentation is missing

### ISSUE THREAD

**Issue by MCSH** [GochoMugo/node-telegram-bot-api#36]
Hello

In the original repo from yagop there is a `callback_query` which I don't see in the documentation of this repo, but is inside the source code. Is it safe to use?  And what does it provide to the callback function?

Thanks in advance

**Comment by GochoMugo** [comment]
The `callback_query` provided here is basically the same provided by the original repo. You could use the original repo's documentation. I am currently helping get the original repo updated, so bear with us if some features and bug fixes have not been published to npm.

**Comment by GochoMugo** [comment]
We are deprecating this repository, as the original repository is now up-to-date. We will be waiting for you there. :smile:
